#pragma once

//TODO move me to client and to BlockGraphics!!

///Render layers: be aware that the order *is important* to the merged rendering
enum BlockRenderLayer {
	RENDERLAYER_DOUBLE_SIDED = 0,
	RENDERLAYER_BLEND,
	RENDERLAYER_WATER,
	RENDERLAYER_OPAQUE,
	RENDERLAYER_ENDPORTAL,
	RENDERLAYER_OPTIONAL_ALPHATEST,
	RENDERLAYER_ALPHATEST,
	RENDERLAYER_SEASONS_OPAQUE,
	RENDERLAYER_SEASONS_OPTIONAL_ALPHATEST,
	RENDERLAYER_ALPHATEST_SINGLE_SIDE,
	RENDERLAYER_LAVA,

	_RENDERLAYER_COUNT
};


