#include "Dungeons.h"
#include "world/level/block/LevelEvent.h"

LevelSoundEvent soundEventFromString(const std::string& type) {
	 static std::unordered_map<std::string, LevelSoundEvent> strToEvent = {
		 { "item.use.on"						,LevelSoundEvent::ItemUseOn },
		 { "hit"								,LevelSoundEvent::Hit },
		 { "step"								,LevelSoundEvent::Step },
		 { "jump"								,LevelSoundEvent::Jump },
		 { "break"								,LevelSoundEvent::Break },
		 { "place"								,LevelSoundEvent::Place },
		 { "heavy.step"							,LevelSoundEvent::HeavyStep },
		 { "gallop"								,LevelSoundEvent::Gallop },
		 { "fall"								,LevelSoundEvent::Fall },
		 { "hurt"								,LevelSoundEvent::Hurt },
		 { "hurt.in.water"						,LevelSoundEvent::HurtInWater },
		 { "death"								,LevelSoundEvent::Death },
		 { "death.in.water"						,LevelSoundEvent::DeathInWater },
		 { "death.to.zombie"					,LevelSoundEvent::DeathToZombie },
		 { "ambient"							,LevelSoundEvent::Ambient },
		 { "ambient.baby" 						,LevelSoundEvent::AmbientBaby },
		 { "ambient.in.water"					,LevelSoundEvent::AmbientInWater },
		 { "breathe"							,LevelSoundEvent::Breathe },
		 { "mad"								,LevelSoundEvent::Mad },
		 { "boost"								,LevelSoundEvent::Boost },
		 { "bow"								,LevelSoundEvent::Bow },
		 { "squish.big "						,LevelSoundEvent::SquishBig },
		 { "squish.small"						,LevelSoundEvent::SquishSmall },
		 { "fall.big"							,LevelSoundEvent::FallBig },
		 { "fall.small"							,LevelSoundEvent::FallSmall },
		 { "splash"								,LevelSoundEvent::Splash },
		 { "fizz"								,LevelSoundEvent::Fizz },
		 { "flap"								,LevelSoundEvent::Flap },
		 { "swim"								,LevelSoundEvent::Swim },
		 { "drink"								,LevelSoundEvent::Drink },
		 { "eat"								,LevelSoundEvent::Eat },
		 { "takeoff"							,LevelSoundEvent::Takeoff },
		 { "shake"								,LevelSoundEvent::Shake },
		 { "plop"								,LevelSoundEvent::Plop },
		 { "land"								,LevelSoundEvent::Land },
		 { "saddle"								,LevelSoundEvent::Saddle },
		 { "armor"								,LevelSoundEvent::Armor },
		 { "add.chest"							,LevelSoundEvent::AddChest },
		 { "throw"								,LevelSoundEvent::Throw },
		 { "attack"								,LevelSoundEvent::Attack },
		 { "attack.nodamage"					,LevelSoundEvent::AttackNoDamage },
		 { "warn"								,LevelSoundEvent::Warn },
		 { "shear"								,LevelSoundEvent::Shear },
		 { "milk"								,LevelSoundEvent::Milk },
		 { "thunder"							,LevelSoundEvent::Thunder },
		 { "explode"							,LevelSoundEvent::Explode },
		 { "fire"								,LevelSoundEvent::Fire },
		 { "ignite"								,LevelSoundEvent::Ignite },
		 { "fuse"								,LevelSoundEvent::Fuse },
		 { "stare"								,LevelSoundEvent::Stare },
		 { "spawn"								,LevelSoundEvent::Spawn},
		 { "shoot"								,LevelSoundEvent::Shoot },
		 { "break.block"						,LevelSoundEvent::BreakBlock },
		 { "remedy"								,LevelSoundEvent::Remedy },
		 { "unfect"								,LevelSoundEvent::Unfect },
		 { "levelup"							,LevelSoundEvent::LevelUp },
		 { "bow.hit"							,LevelSoundEvent::BowHit },
		 { "bullet.hit"							,LevelSoundEvent::BulletHit },
		 { "extinguish.fire"					,LevelSoundEvent::ExtinguishFire },
		 { "item.fizz"							,LevelSoundEvent::ItemFizz },
		 { "chest.open"							,LevelSoundEvent::ChestOpen },
		 { "chest.closed"						,LevelSoundEvent::ChestClosed },
		 { "power.on"							,LevelSoundEvent::PowerOn },
		 { "power.off"							,LevelSoundEvent::PowerOff },
		 { "attach"								,LevelSoundEvent::Attach },
		 { "detach"								,LevelSoundEvent::Detach },
		 { "deny"								,LevelSoundEvent::Deny },
		 { "tripod"								,LevelSoundEvent::Tripod },
		 { "pop"								,LevelSoundEvent::Pop },
		 { "drop.slot"							,LevelSoundEvent::DropSlot },
		 { "note"								,LevelSoundEvent::Note },
		 { "thorns"								,LevelSoundEvent::Thorns },
		 { "piston.in"							,LevelSoundEvent::PistonIn },
		 { "piston.out"							,LevelSoundEvent::PistonOut },
		 { "portal"								,LevelSoundEvent::Portal },
		 { "water"								,LevelSoundEvent::Water },
		 { "lava.pop"							,LevelSoundEvent::LavaPop },
		 { "lava"								,LevelSoundEvent::Lava },
		 { "burp"								,LevelSoundEvent::Burp },
		 { "bucket.fill.water"					,LevelSoundEvent::BucketFillWater },
		 { "bucket.empty.water"					,LevelSoundEvent::BucketEmptyWater },
		 { "bucket.fill.lava"					,LevelSoundEvent::BucketFillLava },
		 { "bucket.empty.lava"					,LevelSoundEvent::BucketEmptyLava },
		 { "guardian.flop"						,LevelSoundEvent::GuardianFlop },
		 { "elderguardian.curse"				,LevelSoundEvent::GuardianCurse },
		 { "teleport"							,LevelSoundEvent::Teleport },
		 { "shulker.open"						,LevelSoundEvent::ShulkerOpen},
		 { "shulker.close"						,LevelSoundEvent::ShulkerClose},
		 { "mob.warning"						,LevelSoundEvent::MobWarning },
		 { "mob.warning.baby"					,LevelSoundEvent::MobWarningBaby },
		 
		 { "default"				,LevelSoundEvent::Default },
		 { "undefined"				,LevelSoundEvent::Undefined }
	 };
	 auto res = strToEvent.find(Util::toLower(type));
	 if (res != strToEvent.end()) {
		 return res->second;
	 }
	 else {
		 return LevelSoundEvent::Undefined;
	 }
}
