#pragma once

enum class StructurePieceType : int {
	Unknown = 0,

	EndCityPiece = 'ECTP',

	MineshaftRoom = 'MSRM',
	MineshaftCorridor = 'MSCO',
	MineshaftCrossing = 'MSCR',
	MineshaftStairs = 'MSST',

	NetherBridgeCrossing = 'NBCR',
	NetherBridgeStartPiece = 'NBSP',
	NetherBridgeStraight = 'NBST',
	NetherBridgeEndFiller = 'NBEF',
	NetherBridgeRoomCrossing = 'NBRC',
	NetherBridgeStairsRoom = 'NBSR',
	NetherBridgeMonsterThrone = 'NBMT',
	NetherCastleEntrance = 'NCEN',
	NetherCastleStalkRoom = 'NCSR',
	NetherCastleSmallCorridor = 'NCSC',
	NetherCastleSmallCorridorCrossing = 'NCCC',
	NetherCastleSmallCorridorRightTurn = 'NCRT',
	NetherCastleSmallCorridorLeftTurn = 'NCLT',
	NetherCastleCorridorStairs = 'NCST',
	NetherCastleCorridorTBalcony = 'NCBA',

	OceanMonumentBuilding = 'OMBU',
	OceanMonumentEntryRoom = 'OMER',
	OceanMonumentSimpleRoom = 'OMSR',
	OceanMonumentSimpleTopRoom = 'OMTR',
	OceanMonumentDoubleXRoom = 'OM2X',
	OceanMonumentDoubleYRoom = 'OM2Y',
	OceanMonumentDoubleZRoom = 'OM2Z',
	OceanMonumentDoubleXYRoom = 'OMXY',
	OceanMonumentDoubleYZRoom = 'OMYZ',
	OceanMonumentCoreRoom = 'OMCR',
	OceanMonumentWingRoom = 'OMWR',
	OceanMonumentPenthouse = 'OMPH',

	DesertPyramid = 'DSRT',
	Igloo = 'IGLO',
	JunglePyramid = 'JNGL',
	WitchHut = 'WTCH',

	StrongholdStairsDown = 'SHSD',
	StrongholdStartPiece = 'SHSP',
	StrongholdChestCorridor = 'SHCH',
	StrongholdFillerCorridor = 'SHFI',
	StrongholdFiveCrossing = 'SH5C',
	StrongholdLeftTurn = 'SHLT',
	StrongholdRightTurn = 'SHRT',
	StrongholdLibrary = 'SHLI',
	StrongholdPortalRoom = 'SHPR',
	StrongholdPrisonHall = 'SHPH',
	StrongholdRoomCrossing = 'SHRC',
	StrongholdStraight = 'SHST',
	StrongholdStraightStairsDown = 'SHSS',

	VillageWell = 'VIWE',
	VillageStartPiece = 'VISP',
	VillageSimpleHouse = 'VISH',
	VillageSmallTemple = 'VIST',
	VillageBookHouse = 'VIBH',
	VillageSmallHut = 'VIHT',
	VillagePigHouse = 'VIPG',
	VillageDoubleFarmland = 'VIDF',
	VillageFarmland = 'VIFL',
	VillageSmithy = 'VISM',
	VillageTwoRoomHouse = 'VI2R',
	VillageLightPost = 'VILP',
	VillageStraightRoad = 'VISR'
};
